home/urls.py
from django.urls import re_path as url
from . import views

app_name = 'home'
urlpatterns = [
    
    url(r'^$', views.allnotes , name='all_notes'),

]

notes/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include('notes_App.urls' ,namespace= 'notes')),
    path('', include('home.urls' ,namespace= 'home')),
    path('accounts/', include('accounts.urls' ,namespace= 'accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes_App/urls.py
from django.urls import re_path as url
from . import views 


app_name = 'Note'
urlpatterns = [
    
    url(r'^$', views.all_notes , name='all_notes'),
    url(r'^(?P<slug>[-\w]+)/$', views.details, name='note_detail'),
    url(r'^add$', views.add_note , name='note_add'),
    url(r'^(?P<slug>[-\w]+)/comment$', views.add_Comment , name='add_Comment'),
    # url(r'(?P<slug>[-\w]+)/comment/<int:id>/delete/$', views.DeleteComment.as_view() , name='delete_comment'),
    url(r'^(?P<slug>[-\w]+)/edit$', views.edit, name='note_edit'),
    url(r'^(?P<slug>[-\w]+)/delete/$', views.Delete.as_view(), name='delete_note'),
]

notes_App/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils.text import slugify
from ckeditor.fields import RichTextField

# from ckeditor.fields import RichTextField
# Create your models here.
class Note (models.Model):
    user    = models.ForeignKey(User,on_delete=models.CASCADE)
    title   = models.CharField(max_length=50)
    slug    = models.SlugField(null=True,blank=True)
    content = RichTextField()
    crated  = models.DateTimeField(blank=True, default=datetime.datetime.now)
    active  = models.BooleanField(default=True)
    tags    = models.CharField(blank=True, max_length=50)
    
    img     = models.ImageField(upload_to='notes-img/', default='', null=True , blank=True)
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Note, self).save(*args, **kwargs)   
        

    def __str__(self):
        return self.title
    
    
class Comment (models.Model):
    comment = models.TextField(blank=True, max_length=300)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    noteComment = models.ForeignKey(Note,on_delete=models.CASCADE)
    created  = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.comment
    
    
# class Comment(models.Model):
#     post = models.ForeignKey(Note,on_delete=models.CASCADE,related_name='comments')
#     name = models.CharField(max_length=80)
#     email = models.EmailField()
#     body = models.TextField()
#     created_on = models.DateTimeField(auto_now_add=True)
#     active = models.BooleanField(default=False)

#     class Meta:
#         ordering = ['created_on']

#     def __str__(self):
#         return 'Comment {} by {}'.format(self.body, self.name)

notes_App/forms.py
from django import forms
from .models import Note , Comment
from django.contrib import admin
from ckeditor.widgets import CKEditorWidget

class AddNote(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget() )
    class Meta:
        model = Note
        fields = ['title', 'content', 'tags','img','active']


class AddComment(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

notes_App/views.py
from django.shortcuts import render ,redirect , get_object_or_404
from django.http import HttpResponse
from .models import Note , Comment
from .forms import AddNote , AddComment
from django.contrib.auth.models import User
from django.contrib import messages
from accounts.models import Profile
from django.views.generic.edit import DeleteView
from django.contrib.auth.mixins import  LoginRequiredMixin , UserPassesTestMixin
from django.urls import reverse_lazy
# Create your views here.
#  show all notes
def all_notes(request):
    user = request.user
    all_notes = Note.objects.filter(user=user)
    profile = get_object_or_404(Profile , user=user)
    numNotes = all_notes.count()
    
    context = {
        'numNotes':numNotes,
        'all_notes': all_notes,
        'profile':profile,
    }
    return render(request, 'notes.html', context)

#  show one note
def details(request,slug):
    user = request.user
    note = Note.objects.get(slug=slug)
    profile = get_object_or_404(Profile , user=user)
    note = Note.objects.get(slug=slug)
    all_comments = Comment.objects.filter(noteComment=note) 
    count = all_comments.count()
    # up = note.user.username.upper()
    context = {
        'note': note,
        'profile':profile,
        'count':count,
    }
    return render(request, 'one_note.html',context)
    
    
#  delete note
class Delete( UserPassesTestMixin, LoginRequiredMixin ,DeleteView):
    
    model = Note
    context_object_name = 'note'
    success_url = "/"
    template_name = 'delete_note.html'
    def test_func(self):
        note = self.get_object()
        if self.request.user == note.user:
            return True
        else:
            return False

# add note form 
def add_note(request):
    if request.method == 'POST':
        
        form  = AddNote(request.POST,request.FILES)
        if form.is_valid():
            newForm = form.save(commit=False)
            newForm.user = request.user
            form.save()
            messages.info(request, 'Note created successfully')
            return redirect('/notes')
            


            
    else:
        form  = AddNote() 
        
    user = request.user 
    profile = get_object_or_404(Profile , user=user)    
    context = {
        'form': form,
        'profile':profile,
    }
    # Create a toast notification
    # toaster = win10toast.ToastNotifier()
    # toaster.show_toast("Hello", "you Can add note now", duration=10)
    return render(request, 'add_note.html', context)
    

#  Add CommentForm
def add_Comment(request,slug):
    if request.method == 'POST':
        note =get_object_or_404(Note , slug = slug)
        
        all_comments = Comment.objects.filter(noteComment=note)
        comment_form  = AddComment(request.POST)
        if comment_form.is_valid():
            newForm = comment_form.save(commit=False)
            newForm.user = request.user
            newForm.noteComment = note
            comment_form.save()
            # newForm.comment = ''
            messages.info(request, 'Comment created successfully')
            
            
    else:
        note = Note.objects.get(slug=slug)
        all_comments = Comment.objects.filter(noteComment=note)
        comment_form  = AddComment() 
    user = request.user 
    profile = get_object_or_404(Profile , user=user)   
    count = all_comments.count()
    context = {
        'count':count,
        'all_comments': all_comments,
        'comment_form': comment_form,
        'profile':profile,
        'note': note,
    }
    return render(request, 'comment.html', context)
    
### 
#  delete COmment
# class DeleteComment( UserPassesTestMixin, LoginRequiredMixin ,DeleteView):
    
#     model = Comment
#     context_object_name = 'comment'
#     success_url = "/"
#     template_name = 'delete_comment.html'
#     def test_func(self):
#         comment = self.get_object()
#         if self.request.user == comment.user:
#             return True
#         else:
#             return False

###########
def edit(request,slug):
    note =get_object_or_404(Note , slug = slug)
    if request.method == 'POST':
        
        form  = AddNote(request.POST,request.FILES , instance=note)
        if form.is_valid():
            newForm = form.save(commit=False)
            newForm.user = request.user
            form.save()
            messages.info(request, 'Note Updated successfully')
            return redirect('/notes')
    else:
        form  = AddNote(instance=note)
        
        user = request.user 
    profile = get_object_or_404(Profile , user=user)       
    context = {
        'note':note,
        'form': form,
        'profile':profile,
    }
    return render(request, 'create.html', context)

notes_App/templates/add_note.html
{% extends "base.html" %}
{% load  static %}
{% load bootstrap4 %}

{% block body %}
<div class="section-headline text-center" style="padding-top: 100px;">
    <h2>Add Note </h2>                 
</div>
<form method="post" enctype="multipart/form-data">
    <a style="background-color:#222;color:#fff;font-size:16px;padding:10px;border-radius:6px" href="/"> Back</a>
    {{ form.media }}
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary" style="margin:50px 0 ;">
        Add Note
    </button>
    
    {% endbuttons %}

</form>

{% endblock body %}

notes_App/templates/comment.html
{% extends "base.html" %}
{% load  static %}
{% load bootstrap4 %}

{% block body %}
    <div class="section-headline text-center" style="padding-top: 100px;">
        <h2>Leave Comment </h2>                 
    </div>
    <form method="POST" class="mt-5" enctype="multipart/form-data">
        {% csrf_token %}
        {{ comment_form.media }}
        {% bootstrap_form comment_form %}
                        
        {% buttons %}
            <button type="submit" class="btn btn-primary" style="margin:50px 0 ;">
                Leave Comment
            </button>
        {% endbuttons %}
        <p>You have {{count}} comment{{count|pluralize:"s"}}</p>
        {% for comment in all_comments %}
        
            <div class="profile-userpic" style="width:100% ; display:flex" >
                <p style="width:50px ; height:50px ; border-radius:5%; background-color:#eee"> </p>
                <p style="margin-left:10px;margin-top:20px"><span class="fw-bold ">{{ comment.user}}</span> : {{comment.created}}</p>
                {% comment %} <p style="color:red; cursor:pointer " class='ms-5 mt-4 '><i class="fa-solid fa-trash me-2 "></i></p> {% endcomment %}
                {% comment %} <a style="color:red; cursor:pointer " href="{% url 'notes:delete_comment' comment.id %}" class="ready-btn ms-5 mt-4 "><i class="fa-solid fa-trash me-2 "></i></a> {% endcomment %}
            </div>
            <p  style="margin-left:70px;opacity:0.6;width:100% ;">- {{ comment.comment}}</p>
            <hr>
    
    
        {% endfor %} 
    </form>
 


{% endblock body %}

notes_App/templates/create.html
{% extends "base.html" %}
{% load  static %}
{% load bootstrap4 %}

{% block body %}
<div class="section-headline text-center" style="padding-top: 100px;">
    <h2>Updeate Details </h2> 
</div>
    
<form method="post" enctype="multipart/form-data" >
    <a style="background-color:#222;color:#fff;font-size:16px;padding:10px;border-radius:6px" href="{% url 'notes:note_detail' note.slug %} "> Back</a>     
    {{ form.media  }}
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary" style="margin:50px 0 ;">
        Update
    </button>
    
    {% endbuttons %}
</form>
  

{% endblock body %}

notes_App/templates/delete_note.html
{% comment %} {% extends "base.html" %} {% endcomment %}
{% comment %} {% load  static %}
{% load bootstrap4 %} {% endcomment %}


<div class="delete-page" style="max-width:800px; margin:150px auto;background-color:#fafafa;padding: 0 ;border-radius:6px">
    <div class="head-del" style="padding:20px;border-radius:6px;background-color:#ac0000;">
        <h2  style="color:#fff">Delete Note </h2> 
        <a  style="color:#fff" href="{% url 'notes:note_detail' note.slug %} "> Back</a>                
    </div>

    <form method="post"  style="padding:20px" >
        {% csrf_token %}

            <p style="color:#000;">Are you sure you want to delete "{{ note }}"?</p>
            <input type="submit" value="Delete" style="color:#fff; background-color:#ac0000; outline:none ;border:none;border-radius:6px;padding:10px;cursor:pointer">
    </form>
</div>

notes_App/templates/notes.html
{% extends "base.html" %}
{% load  static %}


{% block body %}
    <div class="section-headline text-center" style="padding-top: 100px;">
        <h2> All Notes </h2>                 
    </div>
    {% comment %} <a style="background-color:#222;color:#fff;font-size:16px;padding:10px;border-radius:6px;margin-bottom:50px" href="/"> Home</a> {% endcomment %}
        {% if all_notes %}
                {% for note in all_notes %}
                <!-- Start Left Blog -->
                <div class="col-md-4 col-sm-4 col-xs-12">
                <div class="single-blog">
                    <div class="single-blog-img">
                    <a >
                        {% if note.img %}
                        <img src="{{note.img.url}}" alt="">
                        {% endif %}
                    </a>
                    </div>
                    <div class="blog-meta">

                    <span class="date-type">
                        <i class="fa fa-calendar"></i>{{note.crated}}
                    </span>
                    </div>
                    <div class="blog-text">
                    <h4>
                        <a >{{note.title}}</a>
                    </h4>
                    <h6>
                        
                        {{note.content|safe|truncatewords:'20'}}
                    </h6>
                    </div>
                    <span>
                    <a href="{% url 'notes:note_detail' note.slug %} " class="ready-btn">Read more</a>
                    </span>
                    <p class="date-type" style='margin:10px;' >
                        userName :  {{note.user.username}}
                    </p>

                </div>
                <!-- Start single blog -->
                </div>
                <!-- End Left Blog-->
                {% endfor %}
        {% else %}
        <p style="width:600px ; margin:auto;padding-left:200px"  >You Don't Have Any Notes Yet!</p>
        {% endif %}

{% endblock body %}

notes_App/templates/one_note.html
{% extends "base.html" %}
{% load  static %}
{% load bootstrap4 %}


{% block body %}

<div class="section-headline text-center" style="padding-top: 100px;">
    <h2>Note Details </h2>                 
</div>
                <!-- Start Left Blog -->
                <div class="col-md-20 col-sm-20 col-xs-25" style="margin-top: 50px;">
                <div class="single-blog">
                    <div class="single-blog-img">
                    
                        {% if note.img %}
                            <img src="{{note.img.url}}" alt="">
                        {% endif %}
                    
                    </div>
                    <div class="blog-meta">
                    <span class="date-type">
                        <i class="fa fa-calendar"></i>{{note.crated}}
                    </span>
                    </div>
                    <div class="blog-text">
                    <h1>
                        <a>{{note.title}}</a>
                    </h1>
                    <p style="font-size:24px;font-weight:300;font-family:times;">
                        {{note.content|safe}}
                    </p>
                    <p class="date-type">
                        
                        Active : {{note.active}}
                        
                    </p>
                    <p class="date-type">
                        tages : {{note.tags}}
                    </p>
                    <p class="date-type">
                        UserName : {{note.user.username}}
                    </p>
                    </div>
                    <p>{{count}} comment{{count|pluralize:"s"}}</p>
                    {% if user == note.user %}
                        <span>
                            <a href="{% url 'notes:note_edit' note.slug %}" class="ready-btn">Update Details</a>
                        </span>
                        <span>
                            <a href="{% url 'notes:delete_note' note.slug %}" class="ready-btn">Delete</a>
                        </span> 

                        
                    {% endif %}
                    <a class="ready-btn" href="{% url 'notes:add_Comment' note.slug %}"> Comments</a>

                </div>
                </div>


{% endblock body %}