accounts/urls.py
from django.urls import re_path as url
from . import views
# from django.contrib.auth.views import login , logout
# from django.contrib.auth.views import LoginView ,LoginView
from django.contrib.auth import views as auth_views
# from django.contrib.auth.views import login , logout
app_name = 'accounts'
urlpatterns = [
    
    url(r'^$', views.home , name='home'),
    # url(r'^login/$', login,{'template_name': 'login.html'}, name = 'login'),
    url('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url('logout/', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.register , name='register'),
    url(r'^(?P<slug>[-\w]+)/$', views.profile  , name='profile'),
    url(r'^(?P<slug>[-\w]+)/edit$', views.edit_profile  , name='edit_profile'),
    url(r'^(?P<slug>[-\w]+)/change_password$', views.change_password  , name='change_password'),
]

home/urls.py
from django.urls import re_path as url
from . import views

app_name = 'home'
urlpatterns = [
    
    url(r'^$', views.allnotes , name='all_notes'),

]

notes/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include('notes_App.urls' ,namespace= 'notes')),
    path('', include('home.urls' ,namespace= 'home')),
    path('accounts/', include('accounts.urls' ,namespace= 'accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime
from django.utils.text import  slugify
from django.db.models.signals import  post_save
# Create your models here.
class Profile(models.Model):
    user      = models.OneToOneField(User,on_delete=models.CASCADE)
    slug      = models.SlugField(null=True, blank= True)
    headline = models.CharField(blank=True,max_length=100)
    bio       = models.TextField(blank= True)
    userphoto = models.ImageField(upload_to='profile-img',default='')
    join_date = models.DateTimeField(blank=True , default=datetime.datetime.now)
    
    def save(self, *args , **kwargs):
        if not self.slug:
            self.slug = slugify(self.user)
        super(Profile, self).save(*args, **kwargs)
        
    def __str__(self):
        return '%s' %(self.user)    
    
    
### signal 
def createprofile(sender , **kwargs):
    if kwargs['created']:
        user_profile = Profile.objects.create(user= kwargs['instance'])

post_save.connect(createprofile, sender=User)        

accounts/forms.py
from django import forms
from . import models
from django.contrib.auth.models import  User


class UserForm(forms.ModelForm):
    class  Meta:
        model  = User
        fields = [
            'username' , 'first_name', 'last_name', 'email'
        ]



class ProfileForm(forms.ModelForm):
    class Meta:
        model = models.Profile
        fields = [
            'headline','bio','userphoto'
        ]

accounts/views.py
from django.shortcuts import render ,redirect
from django.contrib.auth.forms import UserCreationForm , PasswordChangeForm
from django.contrib.auth import authenticate , login
from .models import Profile
from django.shortcuts import get_object_or_404
from .forms import UserForm , ProfileForm
from django.contrib.auth.models import User
from django.contrib import messages
from notes_App.models import Note
# Create your views here.
def home(request):
    pass



def register(request):
    if request.method == "POST":
        
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username =form.cleaned_data.get('username') 
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password= password)
            login(request, user)
            messages.info(request, 'register created successfully')
            return redirect('/notes')   
    else:
        form = UserCreationForm
    if request.user.is_authenticated:
        user = request.user
        profile = get_object_or_404(Profile , user=user)
        context = {
            'form': form,
            'profile':profile,
        }
    else:
        context = {
            'form': form,
        }
    return render(request,'signup.html', context)
    

def profile(request, slug):
        
        
        profile = get_object_or_404(Profile, slug=slug)
        context = {
            'profile': profile
        }
        
        return render(request,'profile.html',context)
    
def edit_profile(request,slug):
    profile = get_object_or_404(Profile, slug=slug)
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        profile_form = ProfileForm(request.POST,request.FILES,instance=profile) 
        if user_form.is_valid() and profile_form.is_valid() :
            user_form.save()
            profile_form.save()
            messages.info(request, 'Profile Updated successfully')
            # new_profile.user = request.user
            # new_profile.save()
            return redirect('/')
    else:
        user_form = UserForm(instance=request.user)
        profile_form = ProfileForm(instance=profile)  
        
        context = {
            'user_form':user_form,
            'profile_form':profile_form,
            'profile': profile,
            
        }  
        
        return render(request,'edit_profile.html',context)
    
    
def change_password(request,slug):
    profile = get_object_or_404(Profile, slug=slug)
    if request.method == 'POST':
        form =  PasswordChangeForm(request.user,request.POST)
        if form.is_valid():
            
            form.save()
            messages.info(request, 'Password Updated successfully')
            return redirect('/')
    else:
        form =  PasswordChangeForm(user=request.user)
    
    context = {
        'form': form,
        'profile':profile,
    }
    return render(request,'change_password.html',context)

accounts/templates/change_password.html
{% extends "base.html" %}
{% load  static %}
{% load bootstrap4 %}

{% block body %}
    <div class="section-headline text-center" style="padding-top: 100px;">
        <h2>Change Password </h2>                 
    </div>
<form method="post" >
    <a style="background-color:#222;color:#fff;font-size:16px;padding:10px;border-radius:6px" href="{% url 'accounts:profile' profile.slug %} "> Back</a> 
    {% csrf_token %}
    {% bootstrap_form form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary" style="margin:50px 0 ;">
        Change Password
    </button>
    
    {% endbuttons %}
</form>

{% endblock body %}

accounts/templates/edit_profile.html
{% extends "base.html" %}
{% load  static %}
{% load bootstrap4 %}

{% block body %}
<div class="section-headline text-center" style="padding-top: 100px;">
    <h2>Edit your profile </h2>                 
</div>

<form method="post" enctype="multipart/form-data">
    <a style="background-color:#222;color:#fff;font-size:16px;padding:10px;border-radius:6px" href="{% url 'accounts:profile' profile.slug %} "> Back</a>
    {% csrf_token %}
    {% bootstrap_form user_form %}
    
    {% bootstrap_form profile_form %}
    {% buttons %}
    <button type="submit" class="btn btn-primary" style="margin:50px 0 ;">
        Save Changes
    </button>
    
    {% endbuttons %}
</form>
{% endblock body %}

accounts/templates/login.html
{% extends "base.html" %}
{% load  static %}
{% load bootstrap4 %}

{% block body %}
<div class="section-headline text-center" style="padding-top: 100px;">
    <h2>Login Form </h2>                 
</div>
    <div id="login">
        <h3 class="text-center text-white pt-5">Login form</h3>
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        
                        <form id="login-form" class="form" action="" method="post">
                            {% csrf_token %}
                            <h3 class="text-center text-info">Login</h3>
                            {% bootstrap_form form %}
                            <div class="form-group">
                                {% comment %} <label for="remember-me" class="text-info"><span>Remember me</span> <span><input id="remember-me" name="remember-me" type="checkbox"></span></label><br> {% endcomment %}
                                {% buttons %}
                                <button type="submit" class="btn btn-primary " style="margin:50px 0 ;">
                                    Login
                                </button>
                                
                                {% endbuttons %}
                                {% comment %} <input type="submit" name="submit" class="btn btn-info btn-md" value="Login"> {% endcomment %}
                            </div>
                            <div id="register-link" class="text-right">
                                <a href="{% url 'accounts:register' %}" class="text-info">Register here</a>
                                <br>

                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock body %}

accounts/templates/profile.html
{% extends "base.html" %}
{% load  static %}
{% load bootstrap4 %}

{% block body %}
    <div class="section-headline text-center" style="padding-top: 100px;">
        <h2>profile Details </h2>                 
    </div>




        <div class="container prof_con" >
            <div class="row profile prof_con">
                <div class="col-md-3 prof_con">
                    <div class="profile-sidebar prof_con">
                        <!-- SIDEBAR USERPIC -->
                        <div class="profile-userpic" style="width:100%" >
                            <img style="width:200px ; height:200px ; border-radius:50%;margin-left:150px" src=" {% if profile.userphoto  %} {{profile.userphoto.url}} {% else %} {% static 'assets/img/download.png'  %}   {% endif %}" class="img-responsive" alt=""  >
                        </div>
                        <hr>
                        <!-- END SIDEBAR USERPIC -->
                        <!-- SIDEBAR USER TITLE -->
                        <div class="profile-usertitle">
                            <div class="profile-usertitle-name">
                                USerName : {{profile.user}}
                            </div>
                            <hr>
                            <div class="profile-usertitle-job">
                                Bio : {{profile.bio}}
                            </div>
                            <hr>
                            <div class="profile-usertitle-job">
                                Head Line : {{profile.headline}}
                            </div>
                            <hr>
                            <div class="profile-usertitle-job">
                                Date : {{profile.join_date}}
                            </div>
                            <hr>
                        </div>
                        <!-- END SIDEBAR USER TITLE -->
                        <!-- SIDEBAR BUTTONS -->
                        <div class="profile-userbuttons">
                            <a href="{% url 'accounts:edit_profile' profile.slug %}" class="btn btn-success btn-sm" >Edit profile <a>
                            <a href="{% url 'accounts:change_password' profile.slug %}" class="btn btn-success btn-sm" >Change Password <a>

                        </div>

                    </div>
                </div>
                {% comment %} <div class="col-md-9">
                    {% comment %} <div class="profile-content">
                        Some user related content goes here...
                    </div> {% endcomment %}
                </div> 
            </div>
        </div>

{% endblock body %}

accounts/templates/signup.html
{% extends "base.html" %}
{% load  static %}

{% load bootstrap4 %}

{% block body %}
<div class="section-headline text-center" style="padding-top: 100px;">
  <h2>Register Form </h2>                 
</div>
<form class="form-horizontal"  method="POST">
  {% csrf_token %}
  <fieldset>
    <div id="legend">
      <legend class="">Register</legend>
    </div>

    {% bootstrap_form form %}
    <div class="control-group">
      <!-- Button -->
      <div class="controls">
        <button class="btn btn-success">Register</button>
      </div>
    </div>
  </fieldset>
</form>
{% endblock body %}