accounts/urls.py
from django.urls import re_path as url
from . import views
# from django.contrib.auth.views import login , logout
# from django.contrib.auth.views import LoginView ,LoginView
from django.contrib.auth import views as auth_views
# from django.contrib.auth.views import login , logout
app_name = 'accounts'
urlpatterns = [
    
    url(r'^$', views.home , name='home'),
    # url(r'^login/$', login,{'template_name': 'login.html'}, name = 'login'),
    url('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    url('logout/', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^signup/$', views.register , name='register'),
    url(r'^(?P<slug>[-\w]+)/$', views.profile  , name='profile'),
    url(r'^(?P<slug>[-\w]+)/edit$', views.edit_profile  , name='edit_profile'),
    url(r'^(?P<slug>[-\w]+)/change_password$', views.change_password  , name='change_password'),
]

home/urls.py
from django.urls import re_path as url
from . import views

app_name = 'home'
urlpatterns = [
    
    url(r'^$', views.allnotes , name='all_notes'),

]

notes/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('notes/', include('notes_App.urls' ,namespace= 'notes')),
    path('', include('home.urls' ,namespace= 'home')),
    path('accounts/', include('accounts.urls' ,namespace= 'accounts')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

notes_App/urls.py
from django.urls import re_path as url
from . import views 


app_name = 'Note'
urlpatterns = [
    
    url(r'^$', views.all_notes , name='all_notes'),
    url(r'^(?P<slug>[-\w]+)/$', views.details, name='note_detail'),
    url(r'^add$', views.add_note , name='note_add'),
    url(r'^(?P<slug>[-\w]+)/comment$', views.add_Comment , name='add_Comment'),
    # url(r'(?P<slug>[-\w]+)/comment/<int:id>/delete/$', views.DeleteComment.as_view() , name='delete_comment'),
    url(r'^(?P<slug>[-\w]+)/edit$', views.edit, name='note_edit'),
    url(r'^(?P<slug>[-\w]+)/delete/$', views.Delete.as_view(), name='delete_note'),
]

templates/base.html
{% load  static %}
<!DOCTYPE html>
<html lang="en">
    
<head>

    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1.0" name="viewport">

    <title>Notes</title>
    <meta content="" name="description">
    <meta content="" name="keywords">

    <!-- Favicons -->
    <link href="{% static 'assets/img/try.jpg' %}" rel="icon">
    <link href="{% static 'assets/img/try.jpg' %}" rel="apple-touch-icon"> 
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,400i,600,700|Raleway:300,400,400i,500,500i,700,800,900" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <!-- Vendor CSS Files -->
    <link href="{% static 'assets/vendor/animate.css/animate.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/glightbox/css/glightbox.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendor/swiper/swiper-bundle.min.css' %}" rel="stylesheet">

    <!-- Template Main CSS File -->
    <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
    <link href="{% static 'assets/css/mystyle.css' %}" rel="stylesheet">


</head>

<body>

    <!-- ======= Header ======= -->
    <header id="header" class="fixed-top d-flex align-items-center">
        <div class="container d-flex justify-content-between">

        <div class="logo">
            <h1><a href="/"><span>Quick</span>Notes</a></h1>
            <!-- Uncomment below if you prefer to use an image logo -->
            <!-- <a href="index.html"><img src="assets/img/logo.png" alt="" class="img-fluid"></a>-->
        </div>

        <nav id="navbar" class="navbar">
            {% if  user.is_authenticated %}
            <ul>
                <li><a class="nav-link scrollto" href="{% url 'notes:all_notes' %}">Your Notes</a></li>
                <li><a class="nav-link scrollto" href="{% url 'notes:note_add' %}"> Add Notes</a></li>
                <li><a class="nav-link scrollto" href="{% url 'accounts:profile' profile.slug   %}">Profile</a></li>
                <li><a class="nav-link scrollto" href="{% url 'accounts:logout' %}">Logout</a></li>
            </ul>
            {% else %}
            <ul>
                <li><a class="nav-link scrollto" href="{% url 'accounts:login' %}">Login</a></li>
                <li><a class="nav-link scrollto" href="{% url 'accounts:register' %}">Signup</a></li>
                </ul>
            {% endif %}
            <i class="bi bi-list mobile-nav-toggle"></i>
        </nav><!-- .navbar -->

        </div>
    </header><!-- End Header -->
        <main id="main">
        <!-- ======= Blog Section ======= -->
        <div id="blog" class="blog-area">
        <div class="blog-inner area-padding">
            <div class="blog-overly"></div>
            <div class="container ">
            <div class="row">
                <div class="col-md-12 col-sm-12 col-xs-12">

                </div>
            </div>
            <div class="row">

                {% if messages %}
                    <ul class="messages alert alert-success" style = "margin-top: 100px; "  role="alert">
                        {% for message in messages %}
                        <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                        {% endfor %}
                    </ul>
                {% endif %}
                {% block body %}
                    
                {% endblock body %}
                    

            </div>
            </div>
        </div>
        </div><!-- End Blog Section -->



    </main><!-- End #main -->

    <!-- ======= Footer ======= -->
    <footer>
        <div class="footer-area">
        <div class="container">
            <div class="row">
            <div class="col-md-4">
                <div class="footer-content">
                <div class="footer-head">
                    <div class="footer-logo">
                        <h2><span>Quick</span>Notes</h2>
                    </div>
                    <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis.</p>
                    <div class="footer-icons">
                        <ul>
                            <li>
                            <a href="#"><i class="bi bi-facebook"></i></a>
                            </li>
                            <li>
                            <a href="#"><i class="bi bi-twitter"></i></a>
                            </li>
                            <li>
                            <a href="#"><i class="bi bi-instagram"></i></a>
                            </li>
                            <li>
                            <a href="#"><i class="bi bi-linkedin"></i></a>
                            </li>
                        </ul>
                    </div>
                </div>
                </div>
            </div>
            <!-- end single footer -->
            <div class="col-md-4">
                <div class="footer-content">
                <div class="footer-head">
                    <h4>information</h4>
                    <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor.
                    </p>
                    <div class="footer-contacts">
                    <p><span>Tel:</span> +123 456 789</p>
                    <p><span>Email:</span> contact@example.com</p>
                    <p><span>Working Hours:</span> 9am-5pm</p>
                    </div>
                </div>
                </div>
            </div>
            <!-- end single footer -->

            </div>
        </div>
        </div>
        <div class="footer-area-bottom">
        <div class="container">
            <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="copyright text-center">
                <p>
                    &copy; Copyright <strong>QuickNotes</strong>. All Rights Reserved
                </p>
                </div>
                <div class="credits">
                <!--
                All the links in the footer should remain intact.
                You can delete the links only if you purchased the pro version.
                Licensing information: https://bootstrapmade.com/license/
                Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=eBusiness
                -->
                Designed by <a>Mahmoud Adel</a>
                </div>
            </div>
            </div>
        </div>
        </div>
    </footer><!-- End  Footer -->

    <div id="preloader"></div>
    <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>

    <!-- Vendor JS Files -->
    <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/glightbox/js/glightbox.min.js' %}"></script>
    <script src="{% static 'assets/vendor/isotope-layout/isotope.pkgd.min.js' %}"></script>
    <script src="{% static 'assets/vendor/swiper/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'assets/vendor/php-email-form/validate.js' %}"></script>

    <!-- Template Main JS File -->
    <script src="{% static 'assets/js/main.js' %}"></script>

</body>

</html>